// Code generated by mockery v2.43.2. DO NOT EDIT.

package interfaces_mocks

import (
	interfaces "hex/cms/pkg/interfaces"

	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// MockJwtInterface is an autogenerated mock type for the JwtInterface type
type MockJwtInterface struct {
	mock.Mock
}

type MockJwtInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtInterface) EXPECT() *MockJwtInterface_Expecter {
	return &MockJwtInterface_Expecter{mock: &_m.Mock}
}

// NewWithClaims provides a mock function with given fields: method, claims
func (_m *MockJwtInterface) NewWithClaims(method jwt.SigningMethod, claims jwt.Claims) interfaces.JwtTokenInterface {
	ret := _m.Called(method, claims)

	if len(ret) == 0 {
		panic("no return value specified for NewWithClaims")
	}

	var r0 interfaces.JwtTokenInterface
	if rf, ok := ret.Get(0).(func(jwt.SigningMethod, jwt.Claims) interfaces.JwtTokenInterface); ok {
		r0 = rf(method, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.JwtTokenInterface)
		}
	}

	return r0
}

// MockJwtInterface_NewWithClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWithClaims'
type MockJwtInterface_NewWithClaims_Call struct {
	*mock.Call
}

// NewWithClaims is a helper method to define mock.On call
//   - method jwt.SigningMethod
//   - claims jwt.Claims
func (_e *MockJwtInterface_Expecter) NewWithClaims(method interface{}, claims interface{}) *MockJwtInterface_NewWithClaims_Call {
	return &MockJwtInterface_NewWithClaims_Call{Call: _e.mock.On("NewWithClaims", method, claims)}
}

func (_c *MockJwtInterface_NewWithClaims_Call) Run(run func(method jwt.SigningMethod, claims jwt.Claims)) *MockJwtInterface_NewWithClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(jwt.SigningMethod), args[1].(jwt.Claims))
	})
	return _c
}

func (_c *MockJwtInterface_NewWithClaims_Call) Return(_a0 interfaces.JwtTokenInterface) *MockJwtInterface_NewWithClaims_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJwtInterface_NewWithClaims_Call) RunAndReturn(run func(jwt.SigningMethod, jwt.Claims) interfaces.JwtTokenInterface) *MockJwtInterface_NewWithClaims_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtInterface creates a new instance of MockJwtInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtInterface {
	mock := &MockJwtInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
